import { execFileSync } from 'child_process';
import { Router } from 'express';
import { requireAuth } from '../auth-middleware.js';
import { requireAuthorizedLocalPath, requireJobAccess, stringField } from '../authz.js';
import { commitMessage, git, slugify } from '../git-utils.js';
import { errorMessage, nestedRecord, phaseOutputBody } from './git-job-utils.js';

export const gitJobPrRouter = Router();

gitJobPrRouter.post('/api/git/pr', requireAuth, async (req, res) => {
  const { jobId } = req.body;
  if (typeof jobId !== 'string') return res.status(400).json({ error: 'jobId is required' });

  const access = await requireJobAccess(req, res, jobId, '*, tasks(id, title, type, description)');
  if (!access) return;
  const authorizedLocalPath = requireAuthorizedLocalPath(res, access.member, stringField(access.record, 'local_path'), 'job local_path');
  if (!authorizedLocalPath) return;

  try {
    const task = nestedRecord(access.record, 'tasks');
    const taskId = task ? stringField(task, 'id') : null;
    const taskTitle = task ? stringField(task, 'title') : null;
    const taskType = task ? stringField(task, 'type') : null;
    if (!taskId || !taskTitle || !taskType) return res.status(400).json({ error: 'Job task is missing id, type, or title' });

    const branch = `workstream/${taskId.substring(0, 8)}-${slugify(taskTitle)}`;
    const message = commitMessage(taskType, taskTitle);
    let body = `## ${taskTitle}\n\n${task && typeof task.description === 'string' ? task.description : ''}\n\n`;
    body += phaseOutputBody(access.record.phases_completed);
    body += `---\nGenerated by WorkStream`;

    try {
      await git(['checkout', branch], authorizedLocalPath);
    } catch {
      await git(['checkout', '-b', branch], authorizedLocalPath);
    }

    await git(['add', '-A'], authorizedLocalPath);
    await git(['commit', '-m', message], authorizedLocalPath);
    await git(['push', '-u', 'origin', branch], authorizedLocalPath, 30000);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', message, '--body', body], {
      cwd: authorizedLocalPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    res.json({ ok: true, branch, prUrl });
  } catch (error) {
    res.status(500).json({ error: errorMessage(error) });
  }
});
