import { execFileSync, spawn } from 'child_process';
import { claudeEnv } from '../claude-env.js';
import { git, slugify } from '../git-utils.js';
import { supabase } from '../supabase.js';

export function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : 'Git operation failed';
}

function workstreamBranch(wsName: string): string {
  const slug = slugify(wsName);
  if (!slug) throw new Error('Workstream name cannot be converted to a branch name');
  return `workstream/${slug}`;
}

export async function pushAndCreatePr(workstreamId: string, wsName: string, localPath: string, extraBody?: string): Promise<string> {
  const { data: tasks, error: tasksError } = await supabase
    .from('tasks')
    .select('type, title')
    .eq('workstream_id', workstreamId)
    .eq('status', 'done')
    .order('position', { ascending: true });
  if (tasksError) throw new Error(tasksError.message);

  const branch = workstreamBranch(wsName);
  const title = `workstream: ${wsName}`;
  let body = `## ${wsName}\n\n### Completed Tasks\n\n`;
  if (tasks && tasks.length > 0) {
    for (const task of tasks) body += `- **${task.type}**: ${task.title}\n`;
  } else {
    body += '_No completed tasks._\n';
  }
  if (extraBody) body += `\n${extraBody}`;
  body += `\n---\nGenerated by WorkStream`;

  await git(['push', '-u', 'origin', branch], localPath, 30000);
  const prUrl = execFileSync('gh', ['pr', 'create', '--title', title, '--body', body, '--head', branch], {
    cwd: localPath,
    encoding: 'utf-8',
    timeout: 30000,
  }).trim();
  const { error: updateError } = await supabase.from('workstreams').update({ status: 'complete', pr_url: prUrl }).eq('id', workstreamId);
  if (updateError) throw new Error(updateError.message);
  return prUrl;
}

export async function runWorkstreamReview(localPath: string): Promise<string> {
  const reviewPrompt = `You are reviewing all changes in this branch before a PR is created.

Run /code-review to review all changes on this branch compared to main.
Then fix any issues that the review identified — apply the fixes directly.
After fixing, run the tests to make sure everything still passes.

At the end, output a brief summary of what was reviewed and what was fixed (if anything).`;

  return new Promise<string>((resolve, reject) => {
    const proc = spawn('claude', ['-p', '--output-format', 'text', '--max-turns', '30', '--model', 'opus'], {
      cwd: localPath,
      stdio: ['pipe', 'pipe', 'pipe'],
      env: claudeEnv,
    });
    let stdoutBuffer = '';
    let stderrTail = '';
    const stderrMax = 2048;
    let settled = false;

    const timeout = setTimeout(() => {
      if (settled) return;
      settled = true;
      proc.kill();
      reject(new Error(`Review claude timed out after 10 minutes. stderr: ${stderrTail}`));
    }, 10 * 60 * 1000);

    proc.stdin.write(reviewPrompt);
    proc.stdin.end();
    proc.stdout.on('data', (data: Buffer) => { stdoutBuffer += data.toString(); });
    proc.stderr.on('data', (data: Buffer) => {
      stderrTail += data.toString();
      if (stderrTail.length > stderrMax) stderrTail = stderrTail.slice(-stderrMax);
    });
    proc.on('close', (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      if (code === 0 || code === null) resolve(stdoutBuffer);
      else reject(new Error(`Review claude exited with code ${code}. stderr: ${stderrTail}`));
    });
    proc.on('error', (error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      reject(error);
    });
  });
}
