import { Router } from 'express';
import { execFileSync } from 'child_process';
import { supabase } from '../supabase.js';
import { requireAuth } from '../auth-middleware.js';
import { cleanupWorktree } from '../worktree.js';

export const gitRouter = Router();

function run(args: string[], cwd: string): string {
  return execFileSync('git', args, { cwd, encoding: 'utf-8', timeout: 30000 }).trim();
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').substring(0, 50);
}

// Commit changes
gitRouter.post('/api/git/commit', requireAuth, async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(title, type)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const message = `codesync(${task.type}): ${task.title}`;

    run(['add', '-A'], localPath);
    const sha = run(['commit', '-m', message], localPath);

    res.json({ ok: true, sha, message });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Push to current branch
gitRouter.post('/api/git/push', requireAuth, async (req, res) => {
  const { localPath } = req.body;

  try {
    const output = run(['push'], localPath);
    const branch = run(['branch', '--show-current'], localPath);
    res.json({ ok: true, branch, output });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Create branch + PR
gitRouter.post('/api/git/pr', requireAuth, async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(id, title, type, description)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const shortId = task.id.substring(0, 8);
    const branch = `codesync/${shortId}-${slugify(task.title)}`;
    const message = `codesync(${task.type}): ${task.title}`;

    // Build PR body from phase outputs
    const phases = (job.phases_completed as any[]) || [];
    let body = `## ${task.title}\n\n${task.description || ''}\n\n`;
    body += `### Phase Outputs\n\n`;
    for (const p of phases) {
      const output = typeof p.output === 'string' ? p.output : JSON.stringify(p.output, null, 2);
      body += `**${p.phase}** (attempt ${p.attempt})\n\`\`\`\n${output.substring(0, 2000)}\n\`\`\`\n\n`;
    }
    body += `---\nGenerated by CodeSync`;

    // Handle existing branch: try checkout, fall back to create
    try {
      run(['checkout', branch], localPath);
    } catch {
      run(['checkout', '-b', branch], localPath);
    }

    run(['add', '-A'], localPath);
    run(['commit', '-m', message], localPath);
    run(['push', '-u', 'origin', branch], localPath);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', message, '--body', body], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    res.json({ ok: true, branch, prUrl });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Create PR for an entire workstream
gitRouter.post('/api/git/workstream-pr', requireAuth, async (req, res) => {
  const { workstreamId, localPath } = req.body;

  if (!workstreamId || !localPath) {
    return res.status(400).json({ error: 'workstreamId and localPath are required' });
  }

  try {
    // Fetch workstream
    const { data: ws } = await supabase
      .from('workstreams')
      .select('id, name')
      .eq('id', workstreamId)
      .single();
    if (!ws) return res.status(404).json({ error: 'Workstream not found' });

    // Fetch all done tasks for the PR body
    const { data: tasks } = await supabase
      .from('tasks')
      .select('type, title')
      .eq('workstream_id', workstreamId)
      .eq('status', 'done')
      .order('position', { ascending: true });

    const slug = slugify(ws.name);
    const branch = `codesync/${slug}`;
    const title = `codesync: ${ws.name}`;

    // Build PR body from completed tasks
    let body = `## ${ws.name}\n\n### Completed Tasks\n\n`;
    if (tasks && tasks.length > 0) {
      for (const t of tasks) {
        body += `- **${t.type}**: ${t.title}\n`;
      }
    } else {
      body += '_No completed tasks._\n';
    }
    body += `\n---\nGenerated by CodeSync`;

    // Push the worktree branch and create PR
    run(['push', '-u', 'origin', branch], localPath);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', title, '--body', body, '--head', branch], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    // Optionally clean up the worktree after PR creation
    try {
      cleanupWorktree(
        localPath.replace(`/.worktrees/${slug}`, ''),
        slug,
      );
    } catch { /* cleanup is best-effort */ }

    res.json({ ok: true, branch, prUrl });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});
