import { Router } from 'express';
import { execFileSync } from 'child_process';
import path from 'path';
import { supabase } from '../supabase.js';
import { requireAuth } from '../auth-middleware.js';
import { cleanupWorktree } from '../worktree.js';
import { git, slugify, commitMessage } from '../git-utils.js';

export const gitRouter = Router();

// Commit changes
gitRouter.post('/api/git/commit', requireAuth, async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(title, type)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const message = commitMessage(task.type, task.title);

    await git(['add', '-A'], localPath);
    const sha = await git(['commit', '-m', message], localPath);

    res.json({ ok: true, sha, message });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Push to current branch
gitRouter.post('/api/git/push', requireAuth, async (req, res) => {
  const { localPath } = req.body;

  try {
    const output = await git(['push'], localPath, 30000);
    const branch = await git(['branch', '--show-current'], localPath);
    res.json({ ok: true, branch, output });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Create branch + PR
gitRouter.post('/api/git/pr', requireAuth, async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(id, title, type, description)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const shortId = task.id.substring(0, 8);
    const branch = `codesync/${shortId}-${slugify(task.title)}`;
    const message = commitMessage(task.type, task.title);

    // Build PR body from phase outputs
    const phases = (job.phases_completed as any[]) || [];
    let body = `## ${task.title}\n\n${task.description || ''}\n\n`;
    body += `### Phase Outputs\n\n`;
    for (const p of phases) {
      const output = typeof p.output === 'string' ? p.output : JSON.stringify(p.output, null, 2);
      body += `**${p.phase}** (attempt ${p.attempt})\n\`\`\`\n${output.substring(0, 2000)}\n\`\`\`\n\n`;
    }
    body += `---\nGenerated by CodeSync`;

    // Handle existing branch: try checkout, fall back to create
    try {
      await git(['checkout', branch], localPath);
    } catch {
      await git(['checkout', '-b', branch], localPath);
    }

    await git(['add', '-A'], localPath);
    await git(['commit', '-m', message], localPath);
    await git(['push', '-u', 'origin', branch], localPath, 30000);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', message, '--body', body], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    res.json({ ok: true, branch, prUrl });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Create PR for an entire workstream
gitRouter.post('/api/git/workstream-pr', requireAuth, async (req, res) => {
  const { workstreamId, localPath } = req.body;

  if (!workstreamId || !localPath) {
    return res.status(400).json({ error: 'workstreamId and localPath are required' });
  }

  try {
    // Fetch workstream
    const { data: ws } = await supabase
      .from('workstreams')
      .select('id, name')
      .eq('id', workstreamId)
      .single();
    if (!ws) return res.status(404).json({ error: 'Workstream not found' });

    // Fetch all done tasks for the PR body
    const { data: tasks } = await supabase
      .from('tasks')
      .select('type, title')
      .eq('workstream_id', workstreamId)
      .eq('status', 'done')
      .order('position', { ascending: true });

    const slug = slugify(ws.name);
    const branch = `codesync/${slug}`;
    const title = `codesync: ${ws.name}`;

    // Build PR body from completed tasks
    let body = `## ${ws.name}\n\n### Completed Tasks\n\n`;
    if (tasks && tasks.length > 0) {
      for (const t of tasks) {
        body += `- **${t.type}**: ${t.title}\n`;
      }
    } else {
      body += '_No completed tasks._\n';
    }
    body += `\n---\nGenerated by CodeSync`;

    // Push the worktree branch and create PR
    await git(['push', '-u', 'origin', branch], localPath, 30000);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', title, '--body', body, '--head', branch], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    // Respond first so the client doesn't wait for cleanup
    res.json({ ok: true, branch, prUrl });

    // Clean up the worktree after responding (best-effort)
    try {
      const projectPath = path.dirname(path.dirname(localPath));
      cleanupWorktree(projectPath, slug);
    } catch { /* cleanup is best-effort */ }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});
