import { useMemo } from 'react';
import { buildProjectWorkspaceModalProps } from '../lib/current-project-workspace-props';
import type { CurrentProjectWorkspaceProps } from '../components/project-workspace-types';

export function useProjectWorkspaceModalProps({
  project,
  profile,
  activeWorkstreams,
  members,
  flows,
  customTypes,
  showTaskForm,
  taskFormWorkstream,
  editingTask,
  showAddProject,
  showMembersModal,
  onSaveCustomType,
  onCreateTask,
  onUpdateTaskForm,
  onCloseCreateTask,
  onCloseEditTask,
  onCloseAddProject,
  onCreateProject,
  onCloseMembersModal,
}: CurrentProjectWorkspaceProps) {
  return useMemo(() => buildProjectWorkspaceModalProps({
    project,
    userId: profile.id,
    activeWorkstreams,
    members,
    flows,
    customTypes,
    showTaskForm,
    taskFormWorkstream,
    editingTask,
    showAddProject,
    showMembersModal,
    onSaveCustomType,
    onCreateTask,
    onUpdateTaskForm,
    onCloseCreateTask,
    onCloseEditTask,
    onCloseAddProject,
    onCreateProject,
    onCloseMembersModal,
  }), [
    activeWorkstreams,
    customTypes,
    editingTask,
    flows,
    members,
    onCloseAddProject,
    onCloseCreateTask,
    onCloseEditTask,
    onCloseMembersModal,
    onCreateProject,
    onCreateTask,
    onSaveCustomType,
    onUpdateTaskForm,
    profile.id,
    project,
    showAddProject,
    showMembersModal,
    showTaskForm,
    taskFormWorkstream,
  ]);
}
